services:
  # Redis 服务
  - type: redis
    name: redis
    plan: free
    # 修正 #1: 添加IP允许列表，允许账户内其他服务访问
    ipAllowList: [] 

  # 后端服务
  - type: web
    name: backend
    env: docker
    dockerfilePath: ./Dockerfile.backend
    envVars:
      - key: REDIS_URL
        fromService:
          type: redis
          name: redis
          property: connectionString
      - key: OPENROUTER_API_KEY
        sync: false # 部署时Render会提示你手动输入这个值

    disk:
      name: data
      mountPath: /app/data
      sizeGB: 1

  # 前端服务
  - type: web
    name: frontend
    env: docker
    dockerfilePath: ./Dockerfile.frontend
    # 修正 #2: 我们暂时移除了环境变量，部署成功后会通过界面手动设置
    # 这样可以保证配置文件能100%通过检查